spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: file:///Users/sunilkhobragade/Desktop/workspace/apps-platform-acceleration-spring-configuration-code
          #uri: https://github.com/SunilKhobragade/apps-platform-acceleration-spring-configuration-code.git
